### PR TITLE
Make it work with NextJS (#52)

### PR DESCRIPTION
**Pull request by samipourquoi**
Fixed it by exporting unstyled versions of the component. See my PR for uiwjs/react-markdown-preview too.

To use it with NextJS, you would import the following:
```tsx
// in your component
const MDEditor = dynamic(() => import("@uiw/react-md-editor/lib/esm/unstyled"), { ssr: false });

// in pages/_app.tsx
import '@uiw/react-md-editor/dist/markdown-editor.css'
import "@uiw/react-markdown-preview/dist/markdown.css";
```

It seems to work just fine.

### CODE REVIEW

**Comment by samipourquoi** [comment]
huh

**Comment by jaywcjlove** [comment]
@samipourquoi I don’t want to only support `NextJS`. All my projects do not need to import css.

I wonder if there are other better solutions.

**Comment by namnd** [comment]
> @samipourquoi I don’t want to only support `NextJS`. All my projects do not need to import css.
> 
> I wonder if there are other better solutions.

@jaywcjlove this solution doesn't break anything, i.e. it still works as usual, it just provides another way for nextJS to import the library without css.

**Comment by rafaelguedes** [comment]
@jaywcjlove, can you please consider merging this PR in order to support NextJS?

**Comment by jaywcjlove** [comment]
Not to merge for now, I want to maintain the consistency of my more than 100 component libraries.

@samipourquoi 

When we are developing the project, nextjs is not popular. So I am looking for a better solution

**Comment by rafaelguedes** [comment]
I'm not sure if I understood your point but I guess that this PR won't break anything. 
As @namnd said, it only "provides another way for nextJS to import the library without css".

You will, eventually, lose a lot of potential users and contributors for this project if you don't fix this issue.
NextJS is probably the most popular React framework nowadays. 

If you don't like the solution for the issue given in this PR, can you please think and suggest a better one that suits both your and our needs?

@jaywcjlove

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/issues/52#issuecomment-848969341

The perfect solution.

**Pull request closed without merging**
