### PR TITLE
Preserve initial body overflow value

### LINKED ISSUE #309: Rendering the editor breaks the current body overflow
Hi,

First of all, thanks so much for this amazing lib! 🙌 

I just found out that This line is causing problems because it changes the `body` styles directly by setting the overflow to either `initial` or `hidden`.

https://github.com/uiwjs/react-md-editor/blob/master/src/components/Toolbar/index.tsx#L49

Imagine we have a fixed body layout and we always want the overflow to be hidden... we can't basically use this component.

I could open a PR to fix it but I don't know really which approach would be better... any preference?

Thanks!

### PR DESCRIPTION
**Pull request by nuragic**
Fix #309.

### CODE REVIEW

**Comment by nuragic** [comment]
I made the proposed change and tested it locally in our app, it works for our use case and it should not introduce any breaking changes, so also keep working as before.

**Comment by nuragic** [comment]
Well it seems that it doesn't work as expected on the preview, fixing it now! 😅

**Comment by jaywcjlove** [comment]
@nuragic 👍 thx!

**Comment by nuragic** [comment]
Wow, awesome! 🚀  🤘  Many thanks 💌

**Pull request merged**
